# Generated by Django 6.1 on 2026-08-22 02:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(default='Geral', max_length=100)),
                ('qtd', models.PositiveIntegerField(default=0)),
                ('qtd_minima', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['categoria', 'nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='item_nome_unico')],
            },
        ),
    ]
