# Generated by Django 6.1 on 2026-08-22 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida'), ('AJUSTE', 'Ajuste'), ('CADASTRO', 'Cadastro'), ('EXCLUSAO', 'Exclusao')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(choices=[('app', 'App'), ('bot', 'Bot')], default='app', max_length=10)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='estoque.item')),
            ],
            options={
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['data_hora'], name='idx_hist_data'), models.Index(fields=['item'], name='idx_hist_item')],
            },
        ),
    ]
